"""
Theme engine — design-token driven QSS generator.

Material Design 3 の3層トークン (ref → sys → comp) を
config/design_tokens.json から読み込み、QSS と QPalette に展開する。

設計方針:
- 色・角丸・密度の値は **絶対にこのファイルへ直書きしない**（トークンJSONが単一の真実）
- ライト/ダーク切替は sys レイヤーの参照先差し替えのみで実現
- state layer (hover 8% / pressed 12%) を全ウィジェットに一貫適用

Usage:
    from core.theme_engine import apply_theme
    apply_theme(app, mode="dark")   # or "light"
"""

import json
import re
from pathlib import Path

_TOKENS_FILE = Path(__file__).parent.parent / "config" / "design_tokens.json"
_REF_RE = re.compile(r"\{([a-z_.0-9]+)\}")

_cached_tokens = None


# ---------------------------------------------------------------------------
# Token loading / resolution
# ---------------------------------------------------------------------------

def load_tokens(force_reload=False):
    """design_tokens.json を読み込み、参照 ({ref.palette.xxx}) を解決して返す。"""
    global _cached_tokens
    if _cached_tokens is not None and not force_reload:
        return _cached_tokens

    with open(_TOKENS_FILE, encoding="utf-8") as f:
        raw = json.load(f)

    def lookup(path):
        node = raw
        for key in path.split("."):
            node = node[key]
        return node

    def resolve(value, depth=0):
        if depth > 8:
            raise ValueError(f"Token reference too deep: {value}")
        if isinstance(value, str):
            m = _REF_RE.fullmatch(value)
            if m:
                return resolve(lookup(m.group(1)), depth + 1)
            return value
        if isinstance(value, dict):
            return {k: resolve(v, depth) for k, v in value.items()}
        return value

    _cached_tokens = resolve(raw)
    return _cached_tokens


def get_colors(mode="dark"):
    """解決済みの sys カラーロール辞書を返す。"""
    tokens = load_tokens()
    return tokens["sys"][mode]


# ---------------------------------------------------------------------------
# QSS generation
# ---------------------------------------------------------------------------

def build_qss(mode="dark"):
    """トークンからアプリ全体の QSS 文字列を生成する。"""
    t = load_tokens()
    c = t["sys"][mode]
    shape = t["shape"]
    typ = t["type"]
    den = t["density"]

    v = {
        # colors
        "primary": c["primary"],
        "on_primary": c["on_primary"],
        "primary_container": c["primary_container"],
        "on_primary_container": c["on_primary_container"],
        "surface": c["surface"],
        "surface_low": c["surface_container_low"],
        "surface_mid": c["surface_container"],
        "surface_high": c["surface_container_high"],
        "on_surface": c["on_surface"],
        "on_surface_variant": c["on_surface_variant"],
        "on_surface_dim": c["on_surface_dim"],
        "outline": c["outline"],
        "outline_variant": c["outline_variant"],
        "error": c["error"],
        "selection": c["selection"],
        "on_selection": c["on_selection"],
        "hover": c["state_hover"],
        "pressed": c["state_pressed"],
        "focus": c["state_focus"],
        # shape
        "r_s": shape["corner_small"],
        "r_m": shape["corner_medium"],
        "r_l": shape["corner_large"],
        # type
        "font": typ["family"],
        "title_px": typ["title_px"],
        "body_px": typ["body_px"],
        "label_px": typ["label_px"],
        # density
        "row_h": den["list_row_h"],
        "tree_row_h": den["tree_row_h"],
        "toolbar_h": den["toolbar_h"],
        "input_h": den["input_h"],
        "button_h": den["button_h"],
    }

    qss = """
/* ===== generated by core/theme_engine.py — DO NOT EDIT COLORS HERE ===== */

QWidget {{
    background-color: {surface};
    color: {on_surface};
    font-family: {font};
    font-size: {body_px}px;
}}

QMainWindow, QDialog {{ background-color: {surface}; }}

/* ---------- Top app bar (toolbar) ---------- */
QToolBar {{
    background-color: {surface_low};
    border: none;
    min-height: {toolbar_h}px;
    spacing: 4px;
    padding: 2px 6px;
}}
QToolButton {{
    background: transparent;
    border: none;
    border-radius: {r_s}px;
    padding: 4px 8px;
    color: {on_surface_variant};
}}
QToolButton:hover {{ background-color: {hover}; color: {on_surface}; }}
QToolButton:pressed {{ background-color: {pressed}; }}
QToolButton:checked {{
    background-color: {primary_container};
    color: {on_primary_container};
}}

/* ---------- Buttons ---------- */
QPushButton {{
    background-color: {surface_high};
    color: {on_surface};
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    min-height: {button_h}px;
    padding: 2px 14px;
}}
QPushButton:hover {{ background-color: {hover}; }}
QPushButton:pressed {{ background-color: {pressed}; }}
QPushButton:default {{
    background-color: {primary};
    color: {on_primary};
    border: none;
    font-weight: 600;
}}
QPushButton:disabled {{ color: {on_surface_dim}; border-color: {outline_variant}; }}

/* ---------- Inputs ---------- */
QLineEdit, QSpinBox, QComboBox, QTextEdit, QPlainTextEdit {{
    background-color: {surface_low};
    color: {on_surface};
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    min-height: {input_h}px;
    padding: 1px 6px;
    selection-background-color: {selection};
    selection-color: {on_selection};
}}
QLineEdit:focus, QSpinBox:focus, QComboBox:focus, QTextEdit:focus {{
    border: 1px solid {primary};
}}
QComboBox::drop-down {{ border: none; width: 18px; }}
QComboBox QAbstractItemView {{
    background-color: {surface_high};
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    selection-background-color: {selection};
    selection-color: {on_selection};
}}

/* ---------- Item views (browser / tree / list) ---------- */
QTreeView, QListView, QColumnView, QTableView, QListWidget, QTreeWidget, QTableWidget {{
    background-color: {surface};
    alternate-background-color: {surface_low};
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    outline: 0;
}}
QTreeView::item {{ min-height: {tree_row_h}px; border-radius: {r_s}px; }}
QListView::item, QTableView::item {{ min-height: {row_h}px; border-radius: {r_s}px; }}
QTreeView::item:hover, QListView::item:hover, QTableView::item:hover,
QListWidget::item:hover, QTreeWidget::item:hover {{
    background-color: {hover};
}}
QTreeView::item:selected, QListView::item:selected, QTableView::item:selected,
QListWidget::item:selected, QTreeWidget::item:selected {{
    background-color: {selection};
    color: {on_selection};
}}
QHeaderView::section {{
    background-color: {surface_low};
    color: {on_surface_variant};
    border: none;
    border-bottom: 1px solid {outline_variant};
    padding: 4px 8px;
    font-size: {label_px}px;
    font-weight: 600;
}}

/* ---------- Docks / panels ---------- */
QDockWidget {{ titlebar-close-icon: none; }}
QDockWidget::title {{
    background-color: {surface_low};
    color: {on_surface_variant};
    padding: 5px 10px;
    font-size: {label_px}px;
    font-weight: 600;
}}
QSplitter::handle {{ background-color: {outline_variant}; }}
QSplitter::handle:horizontal {{ width: 1px; }}
QSplitter::handle:vertical {{ height: 1px; }}

/* ---------- Tabs ---------- */
QTabWidget::pane {{
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    top: -1px;
}}
QTabBar::tab {{
    background: transparent;
    color: {on_surface_variant};
    padding: 6px 16px;
    border-bottom: 2px solid transparent;
}}
QTabBar::tab:hover {{ background-color: {hover}; }}
QTabBar::tab:selected {{
    color: {primary};
    border-bottom: 2px solid {primary};
    font-weight: 600;
}}

/* ---------- Menus ---------- */
QMenuBar {{ background-color: {surface_low}; }}
QMenuBar::item {{ padding: 4px 10px; border-radius: {r_s}px; }}
QMenuBar::item:selected {{ background-color: {hover}; }}
QMenu {{
    background-color: {surface_high};
    border: 1px solid {outline_variant};
    border-radius: {r_m}px;
    padding: 4px;
}}
QMenu::item {{ padding: 5px 24px 5px 12px; border-radius: {r_s}px; }}
QMenu::item:selected {{ background-color: {selection}; color: {on_selection}; }}
QMenu::separator {{ height: 1px; background: {outline_variant}; margin: 4px 8px; }}

/* ---------- Scrollbars ---------- */
QScrollBar:vertical {{ background: transparent; width: 10px; margin: 0; }}
QScrollBar:horizontal {{ background: transparent; height: 10px; margin: 0; }}
QScrollBar::handle {{
    background: {outline};
    border-radius: 5px;
    min-height: 24px;
    min-width: 24px;
}}
QScrollBar::handle:hover {{ background: {on_surface_dim}; }}
QScrollBar::add-line, QScrollBar::sub-line {{ height: 0; width: 0; }}
QScrollBar::add-page, QScrollBar::sub-page {{ background: transparent; }}

/* ---------- Status bar / tooltips ---------- */
QStatusBar {{
    background-color: {surface_low};
    color: {on_surface_variant};
    font-size: {label_px}px;
}}
QToolTip {{
    background-color: {surface_high};
    color: {on_surface};
    border: 1px solid {outline_variant};
    border-radius: {r_s}px;
    padding: 4px 8px;
}}

/* ---------- Misc ---------- */
QGroupBox {{
    border: 1px solid {outline_variant};
    border-radius: {r_m}px;
    margin-top: 10px;
    padding-top: 6px;
    font-weight: 600;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    left: 8px;
    padding: 0 4px;
    color: {on_surface_variant};
}}
QProgressBar {{
    background-color: {surface_low};
    border: none;
    border-radius: {r_s}px;
    text-align: center;
    min-height: 6px;
}}
QProgressBar::chunk {{ background-color: {primary}; border-radius: {r_s}px; }}
QCheckBox::indicator, QRadioButton::indicator {{ width: 16px; height: 16px; }}
""".format(**v)
    return qss


# ---------------------------------------------------------------------------
# Application entry
# ---------------------------------------------------------------------------

def apply_theme(app, mode="dark"):
    """
    QApplication にテーマを適用する。
    Fusion スタイル + トークン由来 QPalette + 生成 QSS の3点セット。
    実行時の再呼び出し（テーマ切替）にも対応。
    """
    from core.compat import QPalette, QColor

    c = get_colors(mode)

    def qc(value):
        # rgba() 文字列は QPalette には使わないため hex のみ対応
        return QColor(value)

    palette = QPalette()
    palette.setColor(QPalette.Window,          qc(c["surface"]))
    palette.setColor(QPalette.WindowText,      qc(c["on_surface"]))
    palette.setColor(QPalette.Base,            qc(c["surface_container_low"]))
    palette.setColor(QPalette.AlternateBase,   qc(c["surface_container"]))
    palette.setColor(QPalette.ToolTipBase,     qc(c["surface_container_high"]))
    palette.setColor(QPalette.ToolTipText,     qc(c["on_surface"]))
    palette.setColor(QPalette.Text,            qc(c["on_surface"]))
    palette.setColor(QPalette.Button,          qc(c["surface_container_high"]))
    palette.setColor(QPalette.ButtonText,      qc(c["on_surface"]))
    palette.setColor(QPalette.BrightText,      qc(c["error"]))
    palette.setColor(QPalette.Link,            qc(c["primary"]))
    palette.setColor(QPalette.Highlight,       qc(c["selection"]))
    palette.setColor(QPalette.HighlightedText, qc(c["on_selection"]))

    app.setStyle("Fusion")
    app.setPalette(palette)
    app.setStyleSheet(build_qss(mode))


def export_qss(mode="dark", out_path=None):
    """生成QSSをファイルへ書き出す（デバッグ・外部利用向け）。"""
    qss = build_qss(mode)
    if out_path:
        Path(out_path).write_text(qss, encoding="utf-8")
    return qss
